services:
  # Database Service (MySQL)
  mysql:
    # DockerHubからイメージを作成
    image: mysql:8.0.27
    platform: linux/x86_64
    # ローカルの3306番ポートをコンテナの3306番ポートに繋ぐ
    ports:
      - "3306:3306"
    # MySQLコンテナの環境変数ファイルを指定
    env_file:
      - ./.env
    volumes:
      # コンテナ起動時にinit.sqlを実行
      - ./backend/db:/docker-entrypoint-initdb.d
      # 永続的にデータを保存する場所を指定
      - mysql_data:/var/lib/mysql

  # Cache Service (Redis)
  redis:
    # DockerHubからイメージを作成
    image: redis:alpine3.21
    container_name: digbeats-redis
    # ローカルの6379番ポートをコンテナの6379番ポートに繋ぐ
    ports:
      - "6379:6379"

# 永続的にデータを保存する場所を作成
volumes:
  mysql_data:
