services:
  mysql:
    image: mysql:8.0.29
    platform: linux/x86_64
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: h2KDShfi2e9hf2bi
      MYSQL_DATABASE: digbeats-v3
      MYSQL_USER: eito
      MYSQL_PASSWORD: nf83hdfaj8sJIHdsa
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7.4.3
    container_name: digbeats-redis
    ports:
      - "6379:6379"

volumes:
  mysql_data:
