export const dummyRecommendation = {
  recommendationId: 123,
  tracks: [
    {
      id: 1,
      title: "Track Title 1",
      artworkUrl: "https://via.placeholder.com/150",
      permalinkUrl: "https://soundcloud.com/artist/track",
      artist: {
        name: "Artist 1",
        avatarUrl: "https://via.placeholder.com/50",
        permalinkUrl: "https://soundcloud.com/artist",
      },
      streamUrl: "https://example.com/stream",
    },
    {
      id: 2,
      title: "Track Title 2",
      artworkUrl: "https://via.placeholder.com/150",
      permalinkUrl: "https://soundcloud.com/artist/track",
      artist: {
        name: "Artist 2",
        avatarUrl: "https://via.placeholder.com/50",
        permalinkUrl: "https://soundcloud.com/artist",
      },
      streamUrl: "https://example.com/stream",
    },
    {
      id: 3,
      title: "Track Title 3",
      artworkUrl: "https://via.placeholder.com/150",
      permalinkUrl: "https://soundcloud.com/artist/track",
      artist: {
        name: "Artist 3",
        avatarUrl: "https://via.placeholder.com/50",
        permalinkUrl: "https://soundcloud.com/artist",
      },
      streamUrl: "https://example.com/stream",
    },
    {
      id: 4,
      title: "Track Title 4",
      artworkUrl: "https://via.placeholder.com/150",
      permalinkUrl: "https://soundcloud.com/artist/track",
      artist: {
        name: "Artist 4",
        avatarUrl: "https://via.placeholder.com/50",
        permalinkUrl: "https://soundcloud.com/artist",
      },
      streamUrl: "https://example.com/stream",
    },
    {
      id: 5,
      title: "Track Title 5",
      artworkUrl: "https://via.placeholder.com/150",
      permalinkUrl: "https://soundcloud.com/artist/track",
      artist: {
        name: "Artist 5",
        avatarUrl: "https://via.placeholder.com/50",
        permalinkUrl: "https://soundcloud.com/artist",
      },
      streamUrl: "https://example.com/stream",
    },
    {
      id: 6,
      title: "Track Title 6",
      artworkUrl: "https://via.placeholder.com/150",
      permalinkUrl: "https://soundcloud.com/artist/track",
      artist: {
        name: "Artist 6",
        avatarUrl: "https://via.placeholder.com/50",
        permalinkUrl: "https://soundcloud.com/artist",
      },
      streamUrl: "https://example.com/stream",
    },
    {
      id: 7,
      title: "Track Title 7",
      artworkUrl: "https://via.placeholder.com/150",
      permalinkUrl: "https://soundcloud.com/artist/track",
      artist: {
        name: "Artist 7",
        avatarUrl: "https://via.placeholder.com/50",
        permalinkUrl: "https://soundcloud.com/artist",
      },
      streamUrl: "https://example.com/stream",
    },
    {
      id: 8,
      title: "Track Title 8",
      artworkUrl: "https://via.placeholder.com/150",
      permalinkUrl: "https://soundcloud.com/artist/track",
      artist: {
        name: "Artist 8",
        avatarUrl: "https://via.placeholder.com/50",
        permalinkUrl: "https://soundcloud.com/artist",
      },
      streamUrl: "https://example.com/stream",
    },
    {
      id: 9,
      title: "Track Title 9",
      artworkUrl: "https://via.placeholder.com/150",
      permalinkUrl: "https://soundcloud.com/artist/track",
      artist: {
        name: "Artist 9",
        avatarUrl: "https://via.placeholder.com/50",
        permalinkUrl: "https://soundcloud.com/artist",
      },
      streamUrl: "https://example.com/stream",
    },
    {
      id: 10,
      title: "Track Title 10",
      artworkUrl: "https://via.placeholder.com/150",
      permalinkUrl: "https://soundcloud.com/artist/track",
      artist: {
        name: "Artist 10",
        avatarUrl: "https://via.placeholder.com/50",
        permalinkUrl: "https://soundcloud.com/artist",
      },
      streamUrl: "https://example.com/stream",
    },
  ],
};
