openapi: 3.0.3

info:
  title: digbeats API
  version: 1.0.0

paths:
  /api/auth:
    post:
      summary: codeVerifier と code を送信する（Cookie に sessionId が返る）
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - codeVerifier
                - code
              properties:
                codeVerifier:
                  type: string
                code:
                  type: string
      responses:
        200:
          description: OK

  /api/users/following:
    get:
      summary: フォロ中のアーティストを取得する
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    avatarUrl:
                      type: string
                      format: uri
                    likedTracksCount:
                      type: integer
                    permalinkUrl:
                      type: string
                      format: uri

  /api/artists:
    get:
      summary: アーティストを取得する
      parameters:
        - name: name
          in: query
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    avatarUrl:
                      type: string
                      format: uri
                    likedTracksCount:
                      type: integer
                    permalinkUrl:
                      type: string
                      format: uri

  /api/users/following/{artistsId}:
    put:
      summary: アーティストをフォローする
      parameters:
        - name: artistsId
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK

  /api/recommendations:
    get:
      summary: レコメンドを取得する
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    trackTitle:
                      type: string
                    artworkUrl:
                      type: string
                    trackPermalinkUrl:
                      type: string
                    artistName:
                      type: string
                    avatarUrl:
                      type: string
                      format: uri
                    artistPermalinkUrl:
                      type: string
                      format: uri
                    widgetUrl:
                      type: string
                      format: uri

  /api/recommendations/history:
    get:
      summary: レコメンド履歴を取得する
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    recommendedAt:
                      type: string
                      format: date-time
                    tracks:
                      type: array
                      items:
                        type: object
                        properties:
                          widgetUrl:
                            type: string
                            format: uri
