name: Build and Deploy Backend to Azure App Service

# トリガー: backendディレクトリに変更があったmainブランチへのpush時
on:
  push:
    branches:
      - main
    paths:
      - "backend/**"

jobs:
  # --------------------------------------------------
  # ジョブ1: Dockerイメージのビルドとプッシュ
  # --------------------------------------------------
  build:
    runs-on: ubuntu-latest
    name: Build and Push Docker Image

    steps:
      # 1. ソースコードのチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Docker Hubへのログイン
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. DockerイメージのビルドとDocker Hubへのプッシュ
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./backend # Dockerfileがあるディレクトリ
          push: true
          # タグの形式: {ユーザー名}/{リポジトリ名}:{コミットID}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/digbeats-v3-backend:${{ github.sha }}

  # --------------------------------------------------
  # ジョブ2: Azure App Serviceへのデプロイ
  # --------------------------------------------------
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Azure App Service
    needs: build # buildジョブの成功を待ってから実行

    steps:
      # 1. Azure App Serviceへデプロイ
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "portfolio-digbeats-backend-app"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }} # 発行プロファイルで認証
          # Docker Hubにプッシュしたイメージを指定
          images: "${{ secrets.DOCKERHUB_USERNAME }}/digbeats-v3-backend:${{ github.sha }}"
